// Mock bookmark data — 2026, mix of recent + older entries
window.BKMK_DATA = {
  user: 'user@example.com',
  total: 312,
  bookmarks: [
    { id: 2087, title: 'The Next Two Years of Software Engineering By Addy Osmani', url: 'https://addyosmani.com/blog/next-two-years/', stars: 5, notes: 'AI coding evolution, profitability over growth, the new graduate calculus.', priority: 'high', tags: ['dev','blogpost'], shot: true, alarm: false, date: '2026-01-12', dateLabel: 'Jan 12, 2026' },
    { id: 2086, title: 'Why TypeScript 5.7 Changes Everything For Library Authors', url: 'https://devblogs.microsoft.com/typescript/', stars: 4, notes: '', priority: 'high', tags: ['dev','typescript'], shot: true, alarm: true, date: '2026-01-09', dateLabel: 'Jan 09, 2026' },
    { id: 2085, title: 'A pixel artist\u2019s guide to color palettes', url: 'https://lospec.com/articles/palette-guide', stars: 5, notes: 'Lospec\u2019s definitive primer. Bookmark forever.', priority: 'med', tags: ['art','gamedev'], shot: true, alarm: false, date: '2026-01-04', dateLabel: 'Jan 04, 2026' },
    { id: 2084, title: 'localtunnel/localtunnel: expose yourself', url: 'https://github.com/localtunnel/localtunnel', stars: 3, notes: '', priority: 'med', tags: ['dev','tools'], shot: false, alarm: false, date: '2025-12-28', dateLabel: 'Dec 28, 2025' },
    { id: 2083, title: 'psenough/teach_yourself_demoscene_in_14_days', url: 'https://github.com/psenough/teach_yourself_demoscene_in_14_days', stars: 5, notes: 'A guide to learning the demoscene from scratch.', priority: 'high', tags: ['dev','demoscene'], shot: true, alarm: true, date: '2025-12-21', dateLabel: 'Dec 21, 2025' },
    { id: 2082, title: 'awesome-demoscene/README.md', url: 'https://github.com/psykon/awesome-demoscene', stars: 5, notes: '', priority: 'high', tags: ['dev','demoscene'], shot: false, alarm: false, date: '2025-12-19', dateLabel: 'Dec 19, 2025' },
    { id: 2081, title: 'Coder un sine scroll sur Amiga (1/5)', url: 'https://www.stashofcode.fr/coder-un-sine-scroll-sur-amiga-1/', stars: 4, notes: 'Falcon production walkthrough. Magician Lord vibes.', priority: 'high', tags: ['dev','amiga','demoscene'], shot: true, alarm: false, date: '2025-12-15', dateLabel: 'Dec 15, 2025' },
    { id: 2080, title: 'Plasma effects in 30 lines of C', url: 'https://lodev.org/cgtutor/plasma.html', stars: 4, notes: '', priority: 'med', tags: ['dev','demoscene'], shot: false, alarm: false, date: '2025-12-11', dateLabel: 'Dec 11, 2025' },
    { id: 2079, title: 'Examples of Real Time Effects', url: 'https://iquilezles.org/articles/', stars: 5, notes: '', priority: 'high', tags: ['dev','demoscene','art'], shot: true, alarm: true, date: '2025-12-09', dateLabel: 'Dec 09, 2025' },
    { id: 2078, title: 'Amiga Hardware Programming | Coppershade', url: 'https://coppershade.org/articles/AMIGA/Tutorials/', stars: 4, notes: '', priority: 'med', tags: ['dev','amiga'], shot: false, alarm: false, date: '2025-12-05', dateLabel: 'Dec 05, 2025' },
    { id: 2077, title: 'Stash of Code \u2014 Bits of help for writing code', url: 'https://www.stashofcode.fr/', stars: 3, notes: '', priority: 'med', tags: ['dev','amiga'], shot: false, alarm: false, date: '2025-12-01', dateLabel: 'Dec 01, 2025' },
    { id: 2076, title: 'WAIT, SKIP et COPJMPx : un usage avanc\u00e9 du Copper', url: 'https://www.stashofcode.fr/copper-amiga-avance/', stars: 3, notes: '', priority: 'med', tags: ['dev','amiga'], shot: false, alarm: false, date: '2025-11-27', dateLabel: 'Nov 27, 2025' },
    { id: 2075, title: 'Les vieilles cracktros ne meurent jamais', url: 'https://canardpc.com/cracktros', stars: 4, notes: 'Entretien avec le cr\u00e9ateur. Vintage.', priority: 'med', tags: ['demoscene','interview'], shot: true, alarm: false, date: '2025-11-22', dateLabel: 'Nov 22, 2025' },
    { id: 2074, title: 'source code asm amiga 500 demoscene', url: 'https://www.google.com/search?q=amiga+500+asm', stars: 2, notes: '', priority: 'low', tags: ['dev','amiga','demoscene'], shot: false, alarm: false, date: '2025-11-15', dateLabel: 'Nov 15, 2025' },
    { id: 2073, title: 'Aminet \u2014 demo/intro/Gemanix.zip', url: 'https://aminet.net/package/demo/intro/Gemanix', stars: 3, notes: '', priority: 'low', tags: ['dev','amiga','demoscene'], shot: false, alarm: false, date: '2025-11-10', dateLabel: 'Nov 10, 2025' },
    { id: 2072, title: 'FastAPI \u2014 ReDoc', url: 'https://fastapi.tiangolo.com/advanced/extending-openapi/', stars: 4, notes: '', priority: 'med', tags: ['dev','python'], shot: true, alarm: false, date: '2025-11-05', dateLabel: 'Nov 05, 2025' },
    { id: 2071, title: 'FastAPI \u2014 Swagger UI', url: 'https://fastapi.tiangolo.com/tutorial/metadata/', stars: 4, notes: '', priority: 'med', tags: ['dev','python'], shot: false, alarm: false, date: '2025-11-02', dateLabel: 'Nov 02, 2025' },
    { id: 2070, title: 'Hosting NextJS on a private server using PM2', url: 'https://blog.logrocket.com/nextjs-pm2/', stars: 3, notes: 'PM2 + Github webhooks for zero-downtime deploys.', priority: 'med', tags: ['dev','nextjs'], shot: false, alarm: false, date: '2025-10-29', dateLabel: 'Oct 29, 2025' },
    { id: 2069, title: 'Sapiendo \u2014 D\u00e9clarer ses versements PER', url: 'https://www.sapiendo.fr/per-declaration', stars: 3, notes: '', priority: 'high', tags: ['impots'], shot: false, alarm: true, date: '2025-10-22', dateLabel: 'Oct 22, 2025' },
    { id: 2068, title: 'Isospiral \u2014 generative spiral playground', url: 'https://isospiral.com', stars: 4, notes: '', priority: 'med', tags: ['dev','canvas'], shot: true, alarm: false, date: '2025-10-18', dateLabel: 'Oct 18, 2025' },
    { id: 2067, title: 'Algorithms \u2014 Philipp K. Janert, Ph.D.', url: 'https://www.principles-of-algorithms.com/', stars: 4, notes: '', priority: 'high', tags: ['dev','book'], shot: false, alarm: false, date: '2025-10-14', dateLabel: 'Oct 14, 2025' },
    { id: 2066, title: 'QR Codes \u2014 Philipp K. Janert, Ph.D.', url: 'https://www.qr-code-book.com/', stars: 3, notes: '', priority: 'low', tags: ['dev','book'], shot: false, alarm: false, date: '2025-10-09', dateLabel: 'Oct 09, 2025' },
    { id: 2065, title: 'Learn LaTeX in 30 minutes \u2014 Overleaf', url: 'https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes', stars: 3, notes: '', priority: 'med', tags: ['dev','latex'], shot: false, alarm: false, date: '2025-10-04', dateLabel: 'Oct 04, 2025' },
    { id: 2064, title: 'Learn / TIC-80 fantasy console', url: 'https://tic80.com/learn', stars: 4, notes: '', priority: 'med', tags: ['dev','gamedev'], shot: true, alarm: false, date: '2025-09-29', dateLabel: 'Sep 29, 2025' },
    { id: 2063, title: 'Why Do Managers Treat Programmers Like Children?', url: 'https://www.youtube.com/watch?v=Qp_yMadY0FA', stars: 3, notes: '', priority: 'med', tags: ['youtube','work'], shot: true, alarm: true, date: '2025-09-24', dateLabel: 'Sep 24, 2025' },
    { id: 2062, title: 'What Is REST API? Crash Course System Design #3', url: 'https://www.youtube.com/watch?v=-mN3VyJuCjM', stars: 5, notes: '', priority: 'high', tags: ['youtube','api'], shot: true, alarm: true, date: '2025-09-19', dateLabel: 'Sep 19, 2025' },
    { id: 2061, title: 'Handmade Hero Complete \u2014 C tutorial', url: 'https://youtube.com/playlist?list=PLnuhp3Xd9PYTt6svyQPyRO_AAuMWGxPzU', stars: 5, notes: '', priority: 'high', tags: ['youtube','tutorial','c'], shot: true, alarm: true, date: '2025-09-15', dateLabel: 'Sep 15, 2025' },
    { id: 2060, title: 'Mr. 4th Programming', url: 'https://www.youtube.com/@Mr4thProgramming/playlists', stars: 5, notes: 'Codebase craft. Subscribe.', priority: 'high', tags: ['youtube'], shot: true, alarm: false, date: '2025-09-10', dateLabel: 'Sep 10, 2025' },
  ],
  reminders: [
    { id: 2087, days: 7 },
    { id: 2069, days: 3 },
    { id: 2062, days: 1 },
    { id: 2061, days: 5 },
  ],
  // tag color tokens — each direction renders these its own way
  tagPalette: {
    dev:        { hue: 215, name: 'dev' },
    blogpost:   { hue: 140, name: 'blogpost' },
    typescript: { hue: 220, name: 'typescript' },
    python:     { hue: 280, name: 'python' },
    nextjs:     { hue: 50,  name: 'nextjs' },
    latex:      { hue: 130, name: 'latex' },
    demoscene:  { hue: 195, name: 'demoscene' },
    amiga:      { hue: 55,  name: 'amiga' },
    canvas:     { hue: 200, name: 'canvas' },
    impots:     { hue: 350, name: 'impots' },
    youtube:    { hue: 290, name: 'youtube' },
    work:       { hue: 30,  name: 'work' },
    tutorial:   { hue: 40,  name: 'tutorial' },
    c:          { hue: 60,  name: 'c' },
    api:        { hue: 155, name: 'api' },
    interview:  { hue: 75,  name: 'interview' },
    art:        { hue: 320, name: 'art' },
    gamedev:    { hue: 10,  name: 'gamedev' },
    book:       { hue: 25,  name: 'book' },
    tools:      { hue: 175, name: 'tools' },
  },
};
